### ISSUE TITLE
concatenate facilitator_1, facilitator_2, etc., into `facilitators` key in JSON

### ISSUE THREAD

**Issue by ryanpitts** [mozilla/mozfest-schedule-loader#3]
... or at least that's how the schedule app's js templates and search functions are currently set up.

e.g. https://github.com/mozilla/mozfest-schedule-app/blob/gh-pages/index.html#L87

That could be reconfigured depending on how we want to display these people's names on session detail pages. For instance, if they're supposed to be displayed as a bullet list, I could see just changing the templates there and leaving the JSON like it is now. @mmmavis any thoughts?

**Comment by mmmavis** [comment]
People want to include their Twitter handle... I wonder if we should process the facilitator fields so they appear in Markdown format? 
eg. `Name, [@twitter_handle](https://twitter.com/@twitter_handle), Organization Name`

Does it make more sense to do this in the Python script or in this block in [`schedule.js`](https://github.com/mozilla/mozfest-schedule-app/blob/gh-pages/js/schedule.js#L91)?

the instruction I put on the spreadsheet for the facilitator is below

```
plz use the exact format as the following (name is required; the other 2 values are optional):
name, @twitter_handle, organization name
```

So, if people do follow the exact format as I noted :eyes: ... we could just grab the first value in this comma separated string as Name, look for "@" for Twitter handle value, and display whatever is left as is?

**Comment by ryanpitts** [comment]
For now I'm adding a concatenated `facilitators` key with _only_ the facilitator names: https://github.com/mozilla/mozfest-schedule-loader/commit/5e5cdb56303057b2be44fdb8559778666615ab93. This should be useful for display on the list pages (and also provides a searchable field for the search input).

Leaving the `facilitator_1`, `facilitator_2`, `facilitator_3` keys in place, in case we need to display the extra information in session detail views.

**Comment by ryanpitts** [comment]
Also added `facilitator_array` key to the JSON in https://github.com/mozilla/mozfest-schedule-loader/commit/2f4bba93e16d768909127636b4a202be2250b16a
