### ISSUE TITLE
12-hour format for 'start' property

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-schedule-loader#4]
@ryanpitts 

Is this possible to format the `start` property so that it's in 12-hour format? So instead of `"start": "14:15"` we format it as `"start": "2:15 PM"`?

**Comment by ryanpitts** [comment]
Yep, I can do that. Had left it alone just in case we preferred 24-hour format for this audience.

**Comment by mmmavis** [comment]
thanks, yea the 24-hr format looks somehow like duration to me :wink: so I think turning it into 12-hr format can help clear that confusion.

![screen shot 2015-10-28 at 4 27 22 pm](https://cloud.githubusercontent.com/assets/2896608/10806212/ceaee6e2-7d90-11e5-8ea0-eb9453b43772.png)

**Comment by ryanpitts** [comment]
Fixed in https://github.com/mozilla/mozfest-schedule-loader/commit/3e57424e6eea3d6cc39229592829e8d3e6be2163. The loader will attempt to coerce times to 12-hour format, but if someone enters weird data into that field for some reason, it should pass through as-is.
